apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: artifactory
  namespace: artifactory
spec:
  gateways:
    - istio-system/tenant
  hosts:
    - artifactory.###ZARF_VAR_DOMAIN###
  http:
    - route:
        - destination:
            host: artifactory.artifactory.svc.cluster.local
            port:
              number: 8082