apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: artifactory-postgres-external-names-exception
  namespace: artifactory
spec:
  exceptions:
  - policyName: restrict-external-names
    ruleNames:
    - external-names
  match:
    any:
    - resources:
        kinds:
        - Service
        namespaces:
        - artifactory
        names:
        - artifactory-postgres
